Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -24,7 +24,9 @@ jobs:
       - name: Install Node Modules
         run: npm install
       - name: Unzip Auth
-        run: unzip -o auth.zip
+        run: |
+          ls -R  # यह चेक करने के लिए कि फाइल वहां है या नहीं
+          unzip -o auth.zip || echo "Zip file not found, skipping unzip"
 
       - name: Run Bot
         run: node index.js
